apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: capstone-bcrypt
  labels:
    app: capstone-bcrypt
spec:
  selector:
    matchLabels:
      app: capstone-bcrypt
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  progressDeadlineSeconds: 1200
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: capstone-bcrypt
    spec:
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - capstone-bcrypt
              - key: "temporary"
                operator: In
                values:
                - "true"
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: udacity
        image: tabiidris/capstone-bcrypt:e7c063b
        command: [
          "/bin/bash", 
          "-c", 
          "npm run serve"
          ]
        imagePullPolicy: Always
        resources:
          limits:
            memory: 64Mi
            cpu: 250m
          requests:
            memory: 32Mi
            cpu: 200m
        ports:
        - containerPort: 80
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            scheme: HTTP
            port: 80
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 2
          timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-bcrypt
spec:
  type: LoadBalancer
  selector:
    app: capstone-bcrypt
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
